// News sources configuration for Indian credit card and points/miles news
// Each source has a type (rss, reddit, or twitter), URL, and category

const SOURCES = [
  // =============================================
  // REDDIT (highest priority - breaks news first)
  // =============================================
  {
    name: 'Reddit - r/CreditCardsIndia',
    type: 'reddit',
    url: 'https://www.reddit.com/r/CreditCardsIndia/new.json?limit=50',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Reddit - r/IndiaInvestments (CC)',
    type: 'reddit',
    url: 'https://www.reddit.com/r/IndiaInvestments/new.json?limit=50',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Reddit - r/india (CC)',
    type: 'reddit',
    url: 'https://www.reddit.com/r/india/new.json?limit=50',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Reddit - r/CreditCardIndia',
    type: 'reddit',
    url: 'https://www.reddit.com/r/CreditCardIndia/new.json?limit=50',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Reddit - r/IndianCreditCards',
    type: 'reddit',
    url: 'https://www.reddit.com/r/IndianCreditCards/new.json?limit=50',
    category: 'credit-card',
    filterKeywords: true,
  },
  // Reddit search queries for broader coverage
  {
    name: 'Reddit Search - Credit Card India',
    type: 'reddit',
    url: 'https://www.reddit.com/search.json?q=credit+card+india&sort=new&limit=25',
    category: 'credit-card',
  },
  {
    name: 'Reddit Search - HDFC Credit Card',
    type: 'reddit',
    url: 'https://www.reddit.com/search.json?q=HDFC+credit+card&sort=new&limit=25',
    category: 'credit-card',
  },
  {
    name: 'Reddit Search - Points Miles India',
    type: 'reddit',
    url: 'https://www.reddit.com/search.json?q=points+miles+india+credit+card&sort=new&limit=25',
    category: 'points-miles',
  },

  // =============================================
  // TWITTER/X (via xcancel.com RSS - Nitter fork)
  // User-specified accounts + additional CC influencers
  // =============================================
  // --- User's hand-picked accounts ---
  {
    name: 'Twitter - @CardsavvyIndia',
    type: 'rss',
    url: 'https://xcancel.com/CardsavvyIndia/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @ProfessorCardz',
    type: 'rss',
    url: 'https://xcancel.com/ProfessorCardz/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @suritalreja',
    type: 'rss',
    url: 'https://xcancel.com/suritalreja/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @EvryPaisaMatter',
    type: 'rss',
    url: 'https://xcancel.com/EvryPaisaMatter/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @LiveFromALounge',
    type: 'rss',
    url: 'https://xcancel.com/LiveFromALounge/rss',
    category: 'points-miles',
  },
  {
    name: 'Twitter - @CardMavenIn',
    type: 'rss',
    url: 'https://xcancel.com/CardMavenIn/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @akshat_money',
    type: 'rss',
    url: 'https://xcancel.com/akshat_money/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @imYadav31',
    type: 'rss',
    url: 'https://xcancel.com/imYadav31/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @TechnoFino',
    type: 'rss',
    url: 'https://xcancel.com/TechnoFino/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @CreditPedia',
    type: 'rss',
    url: 'https://xcancel.com/CreditPedia/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @nikravel',
    type: 'rss',
    url: 'https://xcancel.com/nikravel/rss',
    category: 'points-miles',
  },
  {
    name: 'Twitter - @Boopathy_SA',
    type: 'rss',
    url: 'https://xcancel.com/Boopathy_SA/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @MagnifyClub',
    type: 'rss',
    url: 'https://xcancel.com/MagnifyClub/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @credofly',
    type: 'rss',
    url: 'https://xcancel.com/credofly/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @savesage_club',
    type: 'rss',
    url: 'https://xcancel.com/savesage_club/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @DoBaniye',
    type: 'rss',
    url: 'https://xcancel.com/DoBaniye/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @spendwiselyx',
    type: 'rss',
    url: 'https://xcancel.com/spendwiselyx/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @pointperkspicks',
    type: 'rss',
    url: 'https://xcancel.com/pointperkspicks/rss',
    category: 'points-miles',
  },
  {
    name: 'Twitter - @asktarunn',
    type: 'rss',
    url: 'https://xcancel.com/asktarunn/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @AmazingCreditC',
    type: 'rss',
    url: 'https://xcancel.com/AmazingCreditC/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @milesmintIN',
    type: 'rss',
    url: 'https://xcancel.com/milesmintIN/rss',
    category: 'points-miles',
  },
  {
    name: 'Twitter - @chandrarsrikant',
    type: 'rss',
    url: 'https://xcancel.com/chandrarsrikant/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @luxe_explorer',
    type: 'rss',
    url: 'https://xcancel.com/luxe_explorer/rss',
    category: 'points-miles',
  },
  // --- Additional CC/points influencers & bloggers ---
  {
    name: 'Twitter - @AskTriMan',
    type: 'rss',
    url: 'https://xcancel.com/AskTriMan/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @cardinsider',
    type: 'rss',
    url: 'https://xcancel.com/cardinsider/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @creditcardz_in',
    type: 'rss',
    url: 'https://xcancel.com/creditcardz_in/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @credithelpindia',
    type: 'rss',
    url: 'https://xcancel.com/credithelpindia/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @CardExpert_in',
    type: 'rss',
    url: 'https://xcancel.com/CardExpert_in/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @SBICard_Connect',
    type: 'rss',
    url: 'https://xcancel.com/SBICard_Connect/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @HDFCBank',
    type: 'rss',
    url: 'https://xcancel.com/HDFCBank/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @ICICIBank',
    type: 'rss',
    url: 'https://xcancel.com/ICICIBank/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @AxisBank',
    type: 'rss',
    url: 'https://xcancel.com/AxisBank/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @GetOneCardIN',
    type: 'rss',
    url: 'https://xcancel.com/GetOneCardIN/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @AmexIndia',
    type: 'rss',
    url: 'https://xcancel.com/AmexIndia/rss',
    category: 'credit-card',
  },
  {
    name: 'Twitter - @aubank',
    type: 'rss',
    url: 'https://xcancel.com/aubank/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @IDFCFIRSTBank',
    type: 'rss',
    url: 'https://xcancel.com/IDFCFIRSTBank/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @IndusInd_Bank',
    type: 'rss',
    url: 'https://xcancel.com/IndusInd_Bank/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @YesBank',
    type: 'rss',
    url: 'https://xcancel.com/YesBank/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @KotakBankLtd',
    type: 'rss',
    url: 'https://xcancel.com/KotakBankLtd/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @RBLBankLtd',
    type: 'rss',
    url: 'https://xcancel.com/RBLBankLtd/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @FederalBankLtd',
    type: 'rss',
    url: 'https://xcancel.com/FederalBankLtd/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @RuPay_npci',
    type: 'rss',
    url: 'https://xcancel.com/RuPay_npci/rss',
    category: 'credit-card',
    filterKeywords: true,
  },
  {
    name: 'Twitter - @RBI',
    type: 'rss',
    url: 'https://xcancel.com/RBI/rss',
    category: 'credit-card',
    filterKeywords: true,
  },

  // =============================================
  // GOOGLE NEWS RSS (comprehensive web coverage)
  // =============================================
  {
    name: 'Google News - Credit Card India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Credit Card Rewards India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+rewards+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Credit Card Launch India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+launch+India+new&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Credit Card RBI',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+RBI+regulation&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Amex India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=American+Express+India+credit+card&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - HDFC Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=HDFC+credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - SBI Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=SBI+credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - ICICI Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=ICICI+credit+card&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Axis Bank Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=Axis+Bank+credit+card&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Points Miles India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=frequent+flyer+points+miles+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'points-miles',
  },
  {
    name: 'Google News - Loyalty Program India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=loyalty+program+India+airline+hotel&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'points-miles',
  },
  {
    name: 'Google News - Lounge Access India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=airport+lounge+access+credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },

  // =============================================
  // INDIAN CC/FINANCE BLOGS (RSS)
  // =============================================
  {
    name: 'CardExpert',
    type: 'rss',
    url: 'https://cardexpert.in/feed/',
    category: 'credit-card',
  },
  {
    name: 'LiveFromALounge',
    type: 'rss',
    url: 'https://livefromalounge.com/feed/',
    category: 'points-miles',
  },
  {
    name: 'CardInfo',
    type: 'rss',
    url: 'https://cardinfo.in/feed/',
    category: 'credit-card',
  },

  // =============================================
  // MAJOR INDIAN FINANCE NEWS (keyword-filtered)
  // =============================================
  {
    name: 'Moneycontrol - Personal Finance',
    type: 'rss',
    url: 'https://www.moneycontrol.com/rss/MCtopnews.xml',
    category: 'finance',
    filterKeywords: true,
  },
  {
    name: 'Economic Times - Banking',
    type: 'rss',
    url: 'https://economictimes.indiatimes.com/industry/banking/finance/banking/rssfeeds/13358259.cms',
    category: 'finance',
    filterKeywords: true,
  },
  {
    name: 'NDTV Profit',
    type: 'rss',
    url: 'https://feeds.feedburner.com/ndtvprofit-latest',
    category: 'finance',
    filterKeywords: true,
  },
];

// Keywords to filter articles from general finance/bank sources
const FILTER_KEYWORDS = [
  'credit card',
  'creditcard',
  'debit card',
  'reward point',
  'reward program',
  'loyalty point',
  'loyalty program',
  'lounge access',
  'frequent flyer',
  'air miles',
  'airline miles',
  'hotel points',
  'cashback',
  'cash back',
  'annual fee',
  'joining fee',
  'credit limit',
  'emi',
  'rupay',
  'visa card',
  'mastercard',
  'amex',
  'american express',
  'hdfc card',
  'sbi card',
  'icici card',
  'axis card',
  'kotak card',
  'yes bank card',
  'indusind card',
  'au bank card',
  'idfc card',
  'rbl card',
  'citi card',
  'diners club',
  'infinia',
  'regalia',
  'millennia',
  'swiggy card',
  'flipkart card',
  'amazon card',
  'onecard',
  'fi card',
  'jupiter card',
  'slice card',
  'uni card',
  'cred',
  'marriott bonvoy',
  'vistara',
  'air india',
  'club vistara',
  'intermiles',
  'taj hotel',
  'ihg',
  'hilton honors',
  'accor',
  'reward rate',
  'milestone benefit',
  'welcome benefit',
  'spend based',
  'rbi credit',
  'rbi card',
  'mdr',
  'interchange fee',
  'upi credit',
  'tokenization',
  'co-branded card',
  'super premium card',
  'metal card',
];

module.exports = { SOURCES, FILTER_KEYWORDS };
