// News sources configuration for Indian credit card and points/miles news
// Each source has a type (rss or scrape), URL, and category

const SOURCES = [
  // --- Google News RSS feeds (most comprehensive) ---
  {
    name: 'Google News - Credit Card India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Credit Card Rewards India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+rewards+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Credit Card Launch India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+launch+India+new&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Credit Card RBI',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=credit+card+RBI+regulation&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Amex India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=American+Express+India+credit+card&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - HDFC Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=HDFC+credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - SBI Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=SBI+credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - ICICI Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=ICICI+credit+card&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Axis Bank Credit Card',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=Axis+Bank+credit+card&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },
  {
    name: 'Google News - Points Miles India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=frequent+flyer+points+miles+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'points-miles',
  },
  {
    name: 'Google News - Loyalty Program India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=loyalty+program+India+airline+hotel&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'points-miles',
  },
  {
    name: 'Google News - Lounge Access India',
    type: 'rss',
    url: 'https://news.google.com/rss/search?q=airport+lounge+access+credit+card+India&hl=en-IN&gl=IN&ceid=IN:en',
    category: 'credit-card',
  },

  // --- Indian Finance / Credit Card Blogs ---
  {
    name: 'CardExpert',
    type: 'rss',
    url: 'https://cardexpert.in/feed/',
    category: 'credit-card',
  },
  {
    name: 'LiveFromALounge',
    type: 'rss',
    url: 'https://livefromalounge.com/feed/',
    category: 'points-miles',
  },
  {
    name: 'CardInfo',
    type: 'rss',
    url: 'https://cardinfo.in/feed/',
    category: 'credit-card',
  },

  // --- Major Indian Finance News ---
  {
    name: 'Moneycontrol - Personal Finance',
    type: 'rss',
    url: 'https://www.moneycontrol.com/rss/MCtopnews.xml',
    category: 'finance',
    filterKeywords: true,
  },
  {
    name: 'Economic Times - Banking',
    type: 'rss',
    url: 'https://economictimes.indiatimes.com/industry/banking/finance/banking/rssfeeds/13358259.cms',
    category: 'finance',
    filterKeywords: true,
  },
  {
    name: 'NDTV Profit',
    type: 'rss',
    url: 'https://feeds.feedburner.com/ndtvprofit-latest',
    category: 'finance',
    filterKeywords: true,
  },
];

// Keywords to filter articles from general finance sources
const FILTER_KEYWORDS = [
  'credit card',
  'creditcard',
  'debit card',
  'reward point',
  'reward program',
  'loyalty point',
  'loyalty program',
  'lounge access',
  'frequent flyer',
  'air miles',
  'airline miles',
  'hotel points',
  'cashback',
  'cash back',
  'annual fee',
  'joining fee',
  'credit limit',
  'emi',
  'rupay',
  'visa card',
  'mastercard',
  'amex',
  'american express',
  'hdfc card',
  'sbi card',
  'icici card',
  'axis card',
  'kotak card',
  'yes bank card',
  'indusind card',
  'au bank card',
  'idfc card',
  'rbl card',
  'citi card',
  'diners club',
  'infinia',
  'regalia',
  'millennia',
  'swiggy card',
  'flipkart card',
  'amazon card',
  'onecard',
  'fi card',
  'jupiter card',
  'slice card',
  'uni card',
  'cred',
  'marriott bonvoy',
  'vistara',
  'air india',
  'club vistara',
  'intermiles',
  'taj hotel',
  'ihg',
  'hilton honors',
  'accor',
  'reward rate',
  'milestone benefit',
  'welcome benefit',
  'spend based',
  'rbi credit',
  'rbi card',
  'mdr',
  'interchange fee',
  'upi credit',
  'tokenization',
  'co-branded card',
  'super premium card',
  'metal card',
];

module.exports = { SOURCES, FILTER_KEYWORDS };
